version: '3'
services:

  plugin-linux:
    build:
      context: .
      dockerfile: Dockerfile.linux
    command: bash -c "cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug -DSMTG_ADD_VST3_PLUGINS_SAMPLES=OFF -DSMTG_ADD_VST3_HOSTING_SAMPLES=ON -DSMTG_ADD_VSTGUI=OFF -DSMTG_MYPLUGINS_SRC_PATH=./src -S ./vst3sdk -B ./build && cmake --build ./build --config Debug"
    volumes:
      - ./build:/usr/src/app/build:rw
      - ./src:/usr/src/app/src:rw
      - ./vst3sdk:/usr/src/app/vst3sdk:rw

  plugin-mac:
    build:
      context: .
      dockerfile: Dockerfile.mac

  plugin-win:
    build:
      context: .
      dockerfile: Dockerfile.win
