name: Plugin build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: copy
      run: cp -r vst2sdk/* vst3sdk
    - name: build
      run: mkdir build && cd build && cmake --build . --config Release
    - name: verify
      run: ls ./VST3/Release/
