name: Plugin build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: versions
      run: lsb_release -a && cmake -version && gcc --version
    - name: init
      run: git submodule update --init --recursive
    - name: copy
      run: cp -r vst2sdk/* vst3sdk
    - name: install
      run: mkdir build && cd build && cmake -DSMTG_MYPLUGINS_SRC_PATH=../src ../vst3sdk
    - name: build
      run: ls && cmake --build . --config Release
    - name: verify
      run: ls ./VST3/Release/
