name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

  build_release:
    name: Build release
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            validator_name: validator-linux.zip
            zip_name: plugin-linux.zip
            generator: Unix Makefiles
          - os: macos-latest
            validator_name: validator-mac.zip
            zip_name: plugin-mac.zip
            generator: Xcode
          - os: windows-latest
            validator_name: validator-win.zip
            zip_name: plugin-win.zip
            generator: Visual Studio 16 2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install cmake gcc "libstdc++6" libx11-xcb-dev libxcb-util-dev libxcb-cursor-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libfontconfig1-dev libcairo2-dev libgtkmm-3.0-dev libsqlite3-dev libxcb-keysyms1-dev

      - name: Install macOS dependencies
        if: matrix.os == 'macOS-latest'
        run: brew install cmake

      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install zip

      - name: Setup
        shell: bash
        run: |
          git submodule update --init --recursive
          cp -R -v ./vst2sdk/public.sdk/source/vst2.x ./vst3sdk/public.sdk/source

      - name: Build
        shell: bash
        run: |
          cmake \
            -G "${{ matrix.generator }}" \
            -DCMAKE_BUILD_TYPE=Release \
            -DSMTG_ADD_VST3_PLUGINS_SAMPLES=OFF \
            -DSMTG_ADD_VST3_HOSTING_SAMPLES=ON \
            -DSMTG_ADD_VSTGUI=OFF \
            -DSMTG_MYPLUGINS_SRC_PATH=./src \
            -S ./vst3sdk \
            -B ./build
          cmake --build ./build --config Release

      - name: Metadata
        shell: bash
        run: |
          cp -v ./src/helloworld.png ./build/VST3/Release/plugin.png
          cp -v ./src/helloworld.wav ./build/VST3/Release/plugin.wav
          ./build/bin/Release/validator ./build/VST3/Release/helloworld.vst3 > ./build/VST3/Release/plugin.txt
          node index.js ./build/VST3/Release/helloworld.vst3 ./build/VST3/Release

      - name: Compress plugin
        shell: bash
        run: |
          cd ./build/VST3/Release
          zip -r ../${{ matrix.zip_name }} *

      - name: Compress validator
        if: secrets.CREATE_VALIDATOR == 'true'
        shell: bash
        run: |
          cd ../../bin/Release
          zip -r ../${{ matrix.validator_name }} *

      - name: Upload plugin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build/VST3/${{ matrix.zip_name }}
          asset_name: ${{ matrix.zip_name }}
          asset_content_type: application/zip

      - name: Upload validator
        if: secrets.CREATE_VALIDATOR == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build/bin/${{ matrix.validator_name }}
          asset_name: ${{ matrix.validator_name }}
          asset_content_type: application/zip

      - name: Upload metadata
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build/VST3/Release/plugin.json
          asset_name: plugin.json
          asset_content_type: application/json

      - name: Upload image
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build/VST3/Release/plugin.png
          asset_name: plugin.png
          asset_content_type: image/png

      - name: Upload audio
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build/VST3/Release/plugin.wav
          asset_name: plugin.wav
          asset_content_type: audio/wav
